# Generated by Django 5.2.14 on 2026-05-22 12:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        default="Data Science with 1 Year of Experience",
                        max_length=200,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="I’m a dedicated front-end developer with one year of experience creating professional, responsive web applications. My work focuses on delivering polished user interfaces and seamless user experiences using modern web technologies.",
                    ),
                ),
                ("image", models.ImageField(blank=True, null=True, upload_to="about/")),
                (
                    "tags",
                    models.CharField(
                        blank=True,
                        default="React.js,Next.js,Bootstrap,JavaScript,CSS3,HTML5",
                        max_length=400,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "About Section",
                "verbose_name_plural": "About Sections",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("subject", models.CharField(max_length=250)),
                ("message", models.TextField()),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="Resume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="resumes/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("site_name", models.CharField(default="Muhindi", max_length=100)),
                (
                    "navbar_logo",
                    models.ImageField(blank=True, null=True, upload_to="navbar/"),
                ),
                (
                    "hero_image",
                    models.ImageField(blank=True, null=True, upload_to="hero/"),
                ),
                (
                    "hero_name",
                    models.CharField(
                        blank=True, default="Muhindi John", max_length=100
                    ),
                ),
                (
                    "hero_subtitle",
                    models.CharField(
                        blank=True, default="Data Science", max_length=200
                    ),
                ),
                (
                    "hero_description",
                    models.TextField(
                        blank=True,
                        default="I’m a passionate front-end developer with one year of professional experience building modern, responsive web applications. I specialize in React.js, Next.js, HTML5, CSS3, Bootstrap, and GitHub.",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Site Setting",
                "verbose_name_plural": "Site Settings",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.AddField(
            model_name="project",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="projects/"),
        ),
        migrations.AddField(
            model_name="project",
            name="tags",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="skill",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="skill",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="skills/"),
        ),
        migrations.AddField(
            model_name="skill",
            name="tags",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
